package com.tokkah.kin.net

// Port of mac/Sources/tk/Lpc.swift — lossless fixed-order prediction + Rice
// coding, every packet independent, no lookahead. Bit-exact with the Swift:
// verified against vectors generated by the shipped encoder (see LpcTest).
object Lpc {
    const val MAXN = 256
    fun bound(n: Int): Int = 1 + n * 2

    private fun zig(v: Int): Int = (v shl 1) xor (v shr 31)
    private fun unzig(u: Int): Int = (u ushr 1) xor -(u and 1)

    private fun residual(s: ShortArray, i: Int, p: Int): Int {
        val a = s[i].toInt()
        return when (p) {
            0 -> a
            1 -> a - s[i - 1]
            2 -> a - 2 * s[i - 1] + s[i - 2]
            else -> a - 3 * s[i - 1] + 3 * s[i - 2] - s[i - 3]
        }
    }

    private fun predict(s: ShortArray, i: Int, p: Int): Int = when (p) {
        0 -> 0
        1 -> s[i - 1].toInt()
        2 -> 2 * s[i - 1] - s[i - 2]
        else -> 3 * s[i - 1] - 3 * s[i - 2] + s[i - 3]
    }

    private fun raw(src: ShortArray, n: Int, out: ByteArray): Int {
        out[0] = 0x80.toByte()
        for (i in 0 until n) {
            out[1 + 2 * i] = (src[i].toInt() and 0xff).toByte()
            out[2 + 2 * i] = ((src[i].toInt() shr 8) and 0xff).toByte()
        }
        return 1 + n * 2
    }

    /** Compress [n] samples of [src] into [out]; returns bytes written. */
    fun encode(src: ShortArray, n: Int, out: ByteArray): Int {
        if (n <= 4 || n > MAXN) return raw(src, n, out)
        val uz = IntArray(MAXN)
        var bestBits = Int.MAX_VALUE
        var bestP = 0
        var bestK = 0
        for (p in 0..3) {
            val cnt = n - p
            for (i in p until n) uz[i - p] = zig(residual(src, i, p))
            for (k in 0..15) {
                var bits = cnt * (1 + k)
                for (i in 0 until cnt) bits += uz[i] ushr k
                val total = bits + p * 16 + 8
                if (total >= bestBits) continue
                bestBits = total
                bestP = p; bestK = k
            }
        }
        if (bestBits == Int.MAX_VALUE || (bestBits + 7) / 8 >= bound(n)) return raw(src, n, out)

        val p = bestP; val k = bestK
        out[0] = ((p and 3) or ((k and 31) shl 2)).toByte()
        val w = BitWriter(out, 1)
        for (i in 0 until p) w.put(src[i].toInt() and 0xffff, 16)
        for (i in p until n) {
            val z = zig(residual(src, i, p))
            w.putUnary(z ushr k)
            if (k > 0) w.put(z and ((1 shl k) - 1), k)
        }
        return 1 + w.flush()
    }

    /** Expand [len] bytes of [src] into exactly [n] samples; false on malformed input. */
    fun decode(src: ByteArray, len: Int, n: Int, out: ShortArray): Boolean {
        if (len < 1 || n <= 0 || n > MAXN) return false
        val mode = src[0].toInt() and 0xff
        if (mode and 0x80 != 0) {
            if (len < 1 + n * 2) return false
            for (i in 0 until n) {
                out[i] = ((src[1 + 2 * i].toInt() and 0xff) or (src[2 + 2 * i].toInt() shl 8)).toShort()
            }
            return true
        }
        val p = mode and 3
        val k = (mode shr 2) and 31
        if (k > 15 || n <= p) return false
        val r = BitReader(src, 1, len - 1)
        for (i in 0 until p) {
            val v = r.get(16) ?: return false
            out[i] = v.toShort()
        }
        for (i in p until n) {
            val q = r.getUnary() ?: return false
            var z = q shl k
            if (k > 0) {
                val low = r.get(k) ?: return false
                z = z or low
            }
            out[i] = (unzig(z) + predict(out, i, p)).toShort()
        }
        return true
    }
}

/** MSB-first bit writer over a caller-owned buffer (offset by [base]). */
internal class BitWriter(private val out: ByteArray, private val base: Int) {
    private var byte = 0
    private var acc = 0L
    private var bits = 0
    fun put(v: Int, n: Int) {
        if (n <= 0) return
        val mask = if (n >= 32) 0xffff_ffffL else (1L shl n) - 1
        acc = (acc shl n) or (v.toLong() and mask)
        bits += n
        while (bits >= 8) {
            bits -= 8
            out[base + byte] = (acc shr bits).toByte()
            byte++
        }
    }
    fun putUnary(q: Int) {
        var left = q
        while (left >= 32) { put(0, 32); left -= 32 }
        put(1, left + 1)
    }
    fun flush(): Int {
        if (bits > 0) {
            out[base + byte] = (acc shl (8 - bits)).toByte()
            byte++
            bits = 0
        }
        return byte
    }
}

/** MSB-first reader, every read bounded. */
internal class BitReader(private val src: ByteArray, private val base: Int, private val len: Int) {
    private var pos = 0
    private fun bit(): Int? {
        val idx = pos shr 3
        if (idx >= len) return null
        val b = ((src[base + idx].toInt() and 0xff) shr (7 - (pos and 7))) and 1
        pos++
        return b
    }
    fun get(n: Int): Int? {
        var v = 0
        repeat(n) {
            val b = bit() ?: return null
            v = (v shl 1) or b
        }
        return v
    }
    fun getUnary(): Int? {
        var q = 0
        while (true) {
            val b = bit() ?: return null
            if (b == 1) return q
            q++
            if (q > (1 shl 16)) return null
        }
    }
}
